# Project information
site_name: 'eBGF'
site_description: 'eco Blockchain Governance Framework'
site_author: 'if(is)'
site_url: 'https://internet-sicherheit.github.io/eBGF/'

# Repository
repo_name: 'eBGF'
repo_url: 'https://github.com/internet-sicherheit/eBGF/'

#Site navigation
nav:
    - Home: 
        - Start: index.md
        - About: about.md
    - Framework:
        - 0 General Information:
            - Overview: framework/0/overview.md
            - Conventions: framework/0/conventions.md
        - 1 Organisation: 
            - Organisation Intro: framework/1/Organisation.md
            - Motivation: framework/1/RFC-0111.md
            - Goals: framework/1/RFC-0121.md
            - Values: framework/1/RFC-0131.md
            - Accountability: framework/1/RFC-0141.md
            - Permission-Policy: framework/1/RFC-0151.md
        - 2 Application: 
            - Application Intro: framework/2/Application.md
            - Use Cases: framework/2/RFC-0211.md
            - App developers: framework/2/RFC-0221.md
            - Business models: framework/2/RFC-0231.md
            - Users: framework/2/RFC-0241.md
        - 3 Regulation: 
            - Regulation Intro: framework/3/Regulation.md
            - Antitrust: framework/3/RFC-0311.md
            - AML and KYC: framework/3/RFC-0321.md
            - Privacy (GDPR): framework/3/RFC-0331.md
            - Copyright (DMS): framework/3/RFC-0341.md
            - Services (DSA): framework/3/RFC-0351.md
        - 4 Membership: 
            - Membership Intro: framework/4/Membership.md
            - Onboarding: framework/4/RFC-0411.md
            - Offboarding: framework/4/RFC-0421.md
        - 5 Ecosystem: 
            - Ecosystem Intro: framework/5/Ecosystem.md
            - SDK: framework/5/RFC-0511.md
            - Documentations: framework/5/RFC-0521.md
        - 6 Collaboration: 
            - Collaboration Intro: framework/6/Collaboration.md
            - Communication: framework/6/RFC-0611.md
            - Decision-making: framework/6/RFC-0621.md
            - Onchain/offchain: framework/6/RFC-0631.md
        - 7 Economics: 
            - Economics Intro: framework/7/Economics.md
            - Incentives: framework/7/RFC-0711.md
            - Fees: framework/7/RFC-0721.md
        - 8 Maintenance: 
            - Maintenance Intro: framework/8/Maintenance.md
            - Risk management: framework/8/RFC-0811.md
            - Monitoring: framework/8/RFC-0821.md
        - 9 Standards: 
            - Standards Intro: framework/9/Standards.md
            - Identifiers: framework/9/RFC-0911.md
            - Development: framework/9/RFC-0921.md
        - 10 Protocol: 
            - Protocols Intro: framework/10/Protocol.md
            - Concensus: framework/10/RFC-1011.md
            - Security: framework/10/RFC-1021.md
            - Hardware: framework/10/RFC-1031.md
            - Interoperability: framework/10/RFC-1041.md
            - Permissions: framework/10/RFC-1051.md
            - Scalability: framework/10/RFC-1061.md
        - Glossar: framework/glossar.md
        - Literature: framework/bibliography.md
    - Contact:
        - FAQ: faq.md
        - Contribution: contribute.md
        - Presskit: press.md

#Design
theme:
  name: material
  custom_dir: overrides
  logo: 'https://raw.githubusercontent.com/internet-sicherheit/eBGF/gh-pages/assets/images/EBGF-logo-transparent-white.png'
  favicon: 'https://raw.githubusercontent.com/internet-sicherheit/eBGF/gh-pages/assets/images/EBGF-logo-transparent-white.png'
  features:
    - navigation.tabs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/internet-sicherheit/eBGF
      name: eBGF on GitHub

#Footer
copyright: Site created by the Institute for Internet-Security - if(is). <a href="https://www.internet-sicherheit.de/impressum.html">Imprint</a>. <a href="https://www.internet-sicherheit.de/datenschutz.html">Privacy</a>. Copyright © 2021 <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA-4.0</a>.
